### ISSUE TITLE
NoMethodError: undefined method `instantiate_observers' for ActiveResource::Base:Class

### ISSUE THREAD

**Issue by schristm** [rails/rails-observers#48]
My Gemfile contains the following:

```
gem 'activeresource', github: 'rails/activeresource'
gem 'rails-observers', github: 'rails/rails-observers'
```

I found that a similar issue was reported on the activeresource issue tracker, which seems to have been resolved in the master branch, but using rails-observers master brings back the same error.

**Comment by rafaelfranca** [comment]
Could you provide more information about the error? When it happened? what is the stack trace?

**Comment by schristm** [comment]
It happens when trying to start the server. Here's the full stack trace.

```
rails aborted!
NoMethodError: undefined method `instantiate_observers' for ActiveResource::Base:Class
Did you mean?  instance_variables
/Users/schristm/.rvm/gems/ruby-2.3.1/bundler/gems/rails-observers-f1e4eaa14539/lib/rails/observers/railtie.rb:38:in `block (2 levels) in <class:Railtie>'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:27:in `each'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/Users/schristm/.rvm/gems/ruby-2.3.1/bundler/gems/rails-observers-f1e4eaa14539/lib/rails/observers/railtie.rb:37:in `block in <class:Railtie>'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application/finisher.rb:65:in `block in <module:Finisher>'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
/Users/schristm/Code/panel/config/environment.rb:5:in `<top (required)>'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application.rb:328:in `require_environment!'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
/Users/schristm/Code/panel/bin/rails:9:in `require'
/Users/schristm/Code/panel/bin/rails:9:in `<top (required)>'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
/Users/schristm/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/schristm/Code/panel/bin/spring:13:in `require'
/Users/schristm/Code/panel/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

```

**Comment by rafaelfranca** [comment]
Thanks! Just fixed it.
