### ISSUE TITLE
Broken in rails engine testing environment

### ISSUE THREAD

**Issue by annacrombie** [rails/rails-observers#78]
I am unable to use rails-observers in the Dummy app provided by rails.  I keep getting:

`undefined method `observers=' for ActiveRecord::Base:Class (NoMethodError)`

## version info:

```
ruby 2.6.2p47 (2019-03-13 revision 67232) [i686-linux]
Rails 5.2.3
```

## Steps to reproduce:

1. Create a plugin

`rails plugin new blorgh --mountable`

2. Edit `blorgh.gemspec` and add 'rails-observers' as a dependency

```gemspec
$:.push File.expand_path("lib", __dir__)
require "blorgh/version"
Gem::Specification.new do |spec|
  spec.name        = "blorgh"
  spec.version     = Blorgh::VERSION
  spec.authors     = ["Stone Tickle"]
  spec.email       = ["lattis@mochiro.moe"]
  spec.summary     = "Summary of Blorgh."
  spec.license     = "MIT"

  spec.files = Dir["{app,config,db,lib}/**/*", "MIT-LICENSE", "Rakefile", "README.md"]

  spec.add_dependency "rails", "~> 5.2.3"
  spec.add_dependency "rails-observers"

  spec.add_development_dependency "sqlite3"
end
```

3. edit `test/dummy/config/application.rb` and add an observer

```ruby
require_relative 'boot'

require 'rails/all'

Bundler.require(*Rails.groups)
require "blorgh"

module Dummy
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 5.2

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration can go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded after loading
    # the framework and any gems in your application.
    config.active_record.observers = %i[test_observer]
  end
```

4. run `bin/rails t`

```
Traceback (most recent call last):
        41: from bin/rails:14:in `<main>'
        40: from bin/rails:14:in `require'
        39: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine/commands.rb:9:in `<top (required)>'
        38: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/engine/commands.rb:9:in `require'
        37: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
        36: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
        35: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
        34: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        33: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        32: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        31: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/test/test_command.rb:33:in `perform'
        30: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/test_unit/runner.rb:39:in `run'
        29: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/test_unit/runner.rb:50:in `load_tests'
        28: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/test_unit/runner.rb:50:in `each'
        27: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/test_unit/runner.rb:50:in `block in load_tests'
        26: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/test_unit/runner.rb:50:in `require'
        25: from /home/lattis/dev/rails/blorgh/test/blorgh_test.rb:1:in `<top (required)>'
        24: from /home/lattis/dev/rails/blorgh/test/blorgh_test.rb:1:in `require'
        23: from /home/lattis/dev/rails/blorgh/test/test_helper.rb:7:in `<top (required)>'
        22: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
        21: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
        20: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
        19: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
        18: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/test_help.rb:17:in `<top (required)>'
        17: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:598:in `maintain_test_schema!'
        16: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
        15: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
        14: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
        13: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
        12: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/base.rb:27:in `<top (required)>'
        11: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/base.rb:328:in `<module:ActiveRecord>'
        10: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
         9: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
         8: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
         7: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
         6: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
         5: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
         4: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
         3: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/railtie.rb:123:in `block (2 levels) in <class:Railtie>'
         2: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/railtie.rb:123:in `each'
         1: from /home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/railtie.rb:124:in `block (3 levels) in <class:Railtie>'
/home/lattis/.local/share/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `observers=' for ActiveRecord::Base:Class (NoMethodError)
```

**Comment by annacrombie** [comment]
jk, I was able to fix it by some messing around with `bin/rails` files and fixed it.  Basically I removed all `require rails/XXX` and added one `require rails/all` and that fixed it somehow.

**Comment by annacrombie** [comment]
jk, I was able to fix it by some messing around with `bin/rails` files and fixed it.  Basically I removed all `require rails/XXX` and added one `require rails/all` and that fixed it somehow.

**Comment by JohnSmall** [comment]
> jk, I was able to fix it by some messing around with bin/rails files and fixed it

Anything more specific than that? `bin/rails` in the engine or `bin/rails` in a project that includes the engine. 

I have this problem and I think it's something engine specific, but I'm not sure where.

**Comment by annacrombie** [comment]
To be honest I don't remember the details anymore.  I do remember I was running `bin/rails` in an engine though.

**Comment by Gaurav3khede** [comment]
> > jk, I was able to fix it by some messing around with bin/rails files and fixed it
> 
> Anything more specific than that? `bin/rails` in the engine or `bin/rails` in a project that includes the engine.
> 
> I have this problem and I think it's something engine specific, but I'm not sure where.

Hi ,
 I am also facing the same problem.
 Did you mange to solve it? thanks.
